name: AI Code Agent

on:
  issues:
    types: [labeled]

jobs:
  process-issue:
    if: github.event.label.name == 'ai-agent'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check label
        run: |
          echo "AI Agent triggered!"
          echo "Issue: #${{ github.event.issue.number }}"
          echo "Title: ${{ github.event.issue.title }}"